# Generated by Django 5.2.6 on 2025-09-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbs',
            name='num',
        ),
        migrations.RemoveField(
            model_name='dbs',
            name='txt',
        ),
        migrations.AddField(
            model_name='dbs',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='dbs',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
